mysite/ecommerce/urls.py
from django.urls import path
from .views import add_product, index, contacts, indexProduct, update_product, delete_product, about

app_name="ecommerce"

urlpatterns = [
    #  http://127.0.0.1:8000/
    path('', index, name="index"),

    #  http://127.0.0.1:8000/1/
    path('<int:product_id>/', indexProduct, name="detail"),

    #  http://127.0.0.1:8000/contacts/
    path('contacts/', contacts, name='contacts'),

    path('about/', about, name='about'),

    #  http://127.0.0.1:8000/addproduct/
    path('addproduct/', add_product, name='add_product'),

    #  http://127.0.0.1:8000/updateproduct/1/
    path('updateproduct/<int:product_id>/', update_product, name='update_product'),

    #  http://127.0.0.1:8000/deleteproduct/1/
    path('deleteproduct/<int:product_id>/', delete_product, name='delete_product'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    # http://127.0.0.1:8000/admin/
    path("admin/", admin.site.urls),

    #  http://127.0.0.1:8000/
    path("", include("ecommerce.urls", namespace="ecommerce")),
    path("", include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
from django.urls import path
from .views import register

app_name="users"

urlpatterns = [
    #  http://127.0.0.1:8000/register/
    path('register/', register, name="register"),

]

mysite/ecommerce/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField(default=1)
    description = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self) -> str:
        return self.name

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class": "focus:outline-none", "placeholder": "mail@mail.com"}
        ),
    )
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"class": "focus:outline-none", "placeholder": "Enter username..."}
        ),
    )
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "focus:outline-none", "placeholder": "Enter password"}
        ),
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class": "focus:outline-none", "placeholder": "Enter same password"}
        ),
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    class Meta:
        model = User
        fields =("username", "email", "password1", "password2")

mysite/ecommerce/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Product

def index(request):

    products = Product.objects.all()
    context = {
        "products": products,
    }
    return render(request, "ecommerce/index.html", context=context)

def indexProduct(request, product_id):
    """
    Детальная страница продукта

    """
    product = Product.objects.get(id=product_id)
    context = {
        "product": product
    }
    return render(request, "ecommerce/detail.html", context=context)

def contacts(request):
    """
    Страница с контактными данными

    """
    return render(request, "ecommerce/contacts.html")

def about(request):
    """
    Страница о сайте

    """
    return render(request, "ecommerce/about.html")

def add_product(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES['upload']
        item = Product(name=name, price=price, description=description, image=image)
        item.save()
    return render(request, "ecommerce/addProduct.html")

def update_product(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == "POST":
        product.name = request.POST.get("name")
        product.price = request.POST.get("price")
        product.description = request.POST.get("description")
        product.image = request.FILES.get("upload", product.image)
        product.save()
        return redirect("/")
    context = {
        "product": product
    }
    return render(request, "ecommerce/updateProduct.html", context=context)

def delete_product(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == "POST":
        product.delete()
        return redirect("/")
    context = {
        "product": product
    }
    return render(request, "ecommerce/deleteProduct.html", context=context)

mysite/users/views.py
from django.shortcuts import render
from .forms import NewUserForm

def register(request):
    form = NewUserForm() # создали экземпляр класса-формы
    context = {
        "form": form
    }
    return render(request, "users/register.html", context=context)

mysite/ecommerce/templates/ecommerce/about.html
{% extends 'ecommerce/base.html' %}


{% block content %}

<h1>This is about template</h1>

{% endblock %}

mysite/ecommerce/templates/ecommerce/addProduct.html
{% load static %}
<head> <link rel="stylesheet" href="{% static 'ecommerce/styles.css' %}"> </head>
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Product Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Product Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Product Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Product Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add Product</button>
        </div>
    </form>
</div>

mysite/ecommerce/templates/ecommerce/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'ecommerce/styles.css' %}">
    <title>Document</title>
</head>

<body>

    {% include "ecommerce/navbar.html" %}

    {% block content %}
    TEXT
    {% endblock content %}

</body>

</html>

mysite/ecommerce/templates/ecommerce/contacts.html
{% extends 'ecommerce/base.html'  %}

<h1>This is contacts template</h1>

mysite/ecommerce/templates/ecommerce/deleteProduct.html
{% load static %}
<head> <link rel="stylesheet" href="{% static 'ecommerce/styles.css' %}"> </head>
    <h1 class="text-2xl m-10 font-bold">Delete Product</h1>
    <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray text-sm font mb-2">Are you sure want to delete this product?</label>
            <label class="block text-gray text-sm font mb-2"> {{ product.name }}</label>
            <img class="w-40 h-40" src="{{ product.image.url }}">
        </div>
        <input class=" bg-green-600 text-white px-5 py-3" type="submit" value="Confirm">
        <a class="button bg-red-600 text-white px-5 py-2" href="{% url 'ecommerce:index' %}">Cancel</a>
    </form>
</div>

mysite/ecommerce/templates/ecommerce/detail.html
{% extends 'ecommerce/base.html' %}

{% load humanize %}

{% block content %}

<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{ product.image.url }}" alt="productPhoto">
    <div class="w-2/3 text-xl ml-10 mt-5">
        <p class="mt-5">{{ product.name }}</p>
        <p class="mt-5 text-green-500">$ {{ product.price | intcomma }}</p>
        <p class="mt-5 text-gray-600">{{ product.description }}</p>
        <button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'ecommerce:update_product' product.id %}">Update Item</a></button>
        <button class="bg-red-600 text-white mt-[50px]"><a href="{% url 'ecommerce:delete_product' product.id %}">Delete Item</a></button>

    </div>
</div>

{% endblock content %}

mysite/ecommerce/templates/ecommerce/index.html
{% extends 'ecommerce/base.html'  %}


{% block content %}

<main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
  <div class="sm:text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline">Эсклюзивные товары</span>
      <span class="block xl:inline text-green-500">По Супер Ценам</span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Вы можете заказать товар из любой точки мира. Доставка включена</p>
  </div>
  <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-5">
    {% for product in products %}
      <a href="{% url 'ecommerce:detail' product.id %}">
        <div class=" rounded overflow-hidden shadow-lg">
            <img class="w-full h-[400px]" src="{{product.image.url}}" alt="">
            <div class="px-6 py-4">
              <p class="font-bold text-xl mb-2">{{product.name}}</p>
              <p class="font-bold text-xl text-green-500 mb-2">$ {{product.price}}</p>
              <p class="text-gray-700 text-base">{{ product.description}}</p>
            </div>
          </div>
      </a>
    {% endfor %}
  </div>
</main>



{% endblock content %}

mysite/ecommerce/templates/ecommerce/navbar.html
{% load static %}

<nav class="bg-white shadow-lg">
  <div class="max-w-6xl mx-auto px-4">
    <div class="flex justify-between">
      <div class="flex space-x-7">
        <div>
          <a href="{% url 'ecommerce:index' %}" class="flex items-center px-2 py-4">
            <img
              class="h-8 w-8"
              src="{% static 'ecommerce/images/shop-logo.png' %}"
              alt="logo"
            />
            <span class="text-gray-500 font-semibold text-xl">Pro Shop</span>
          </a>
        </div>
        <div class="items-center flex space-x-1">
          <a
            href="{% url 'ecommerce:index' %}"
            class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500"
            >Home</a
          >
          <a href="{% url 'ecommerce:about' %}" class="py-4 px-2 text-gray-500 font-semibold">About</a>
          <a href="{% url 'ecommerce:contacts' %}" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
        </div>
      </div>
    </div>
  </div>
</nav>

mysite/ecommerce/templates/ecommerce/updateProduct.html
{% load static %}

<head> <link rel="stylesheet" href="{% static 'ecommerce/styles.css' %}"> </head>
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Update Product Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Product Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ product.name }}" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Product Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"  value="{{ product.price }}" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Product Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"  value="{{ product.description }}"  type="text" placeholder="Description..." name="description" id="description">
            <img class="w-20 h-20" src="{{ product.image.url }}" alt=""></img>
            <input class="block mt-4"  type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Update Item" value="Update Item">Update Product</button>
        </div>
    </form>
</div>

mysite/users/templates/users/register.html
{% extends "ecommerce/base.html" %}

{% block content %}
<div class="container py-5">
    <h1 class="text-2xl m-10 font-bold">Register User</h1>
    <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.username}}</p>
            <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Email</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.email}}</p>
            <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Password</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password1}}</p>
            <label class="block text-gray-700 text-sm font-bold mt-5 mb-2">Confirm Password</label>
            <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{form.password2}}</p>
        </div>
        <button class="bg-green-500 text-white px-5 py-2" type="submit">Register</button>
    </form>
</div>
{% endblock content %}